name: Build & Deploy Next.js → S3

on:
  push:
    branches: [main]

env:
  BUCKET_NAME: pranavbedre.in
  REGION: ap-south-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Fetch the latest commit
      - uses: actions/checkout@v4            # :contentReference[oaicite:0]{index=0}

      # 2 Set up Node (caches npm automatically)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3 Install deps & build your statically-exported site
      - name: Install dependencies
        run: npm ci

      - name: Build (creates ./out)
        run: npm run build

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.REGION }}

      # 5 Sync the freshly-built files to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./out s3://$BUCKET_NAME \
            --follow-symlinks  \
            --delete           # removes files that no longer exist locally

      # 6  Invalidate CloudFront cache so viewers see the new build
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DIST_ID }} \
            --paths "/*"
